title                    : "Nolwazi Hlophe"
theme                    : jekyll-theme-cayman
subtitle                 : "Senior Fintech Specialist"
description              : "Fintech | Consumer Protection | Financial Inclusion"
url                      : "https://nolwazihlophe.github.io"
show_downloads           : false

