title                    : "Nolwazi Hlophe"
theme                    : jekyll-theme-cayman
subtitle                 : "Senior Fintech Specialist"
description              : "Financial Inclusion | Fintech | Consumer Protection"
url                      : "https://nolwazihlophe.github.io"
show_downloads           : false

