title: Nolwazi Hlophe
description: Deputy Director Financial Regulation & Supervision | Digital Frontiers
show_downloads: true
google_analytics: 92715204
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
github:
  zip_url: {{ site.github.zip_url }}
  another_url: Publications.md
github:
  zip_url: {{ site.github.tar_url }}
  another_url: Presentations.md
