theme                    : jekyll-theme-cayman
title                    : "Nolwazi Hlophe"
subtitle                 : "Senior Fintech Specialist
description              : "Financial Regulation | Payments | Fintech | Digital Economy | Market Conduct "
url                      : "https://nolwazihlophe.github.io"
logo                     : "NH Logo.png"

